### ISSUE TITLE
请问如何安装这个插件？

### ISSUE THREAD

**Issue by Remoonecho** [litepress/wp-china-yes#111]

**Comment by sunxiyuan** [comment]
1. 下载安装包：[https://a1.wp-china-yes.net/apps/wp-china-yes.zip](https://a1.wp-china-yes.net/apps/wp-china-yes.zip)
 2. 在管理后台->添加插件（左侧菜单中）->上传插件（添加插件页面的左上角）处上传安装。
 3. 启用即可
